version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/ecademy
    env_file:
      - server/.env

  client:
    build: ./client
    ports:
      - "80:80"
    environment:
      - VITE_BACKEND_URL=http://localhost:3001
    depends_on:
      - server
    env_file:
      - client/.env